//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebConsultarDerechosAutor.proxyDerechosAutor {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="proxyDerechosAutor.IWSDerechosAutor")]
    public interface IWSDerechosAutor {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSDerechosAutor/ConsultarFotoHabilitada", ReplyAction="http://tempuri.org/IWSDerechosAutor/ConsultarFotoHabilitadaResponse")]
        bool ConsultarFotoHabilitada(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSDerechosAutor/ConsultarFotoHabilitada", ReplyAction="http://tempuri.org/IWSDerechosAutor/ConsultarFotoHabilitadaResponse")]
        System.Threading.Tasks.Task<bool> ConsultarFotoHabilitadaAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWSDerechosAutorChannel : WebConsultarDerechosAutor.proxyDerechosAutor.IWSDerechosAutor, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSDerechosAutorClient : System.ServiceModel.ClientBase<WebConsultarDerechosAutor.proxyDerechosAutor.IWSDerechosAutor>, WebConsultarDerechosAutor.proxyDerechosAutor.IWSDerechosAutor {
        
        public WSDerechosAutorClient() {
        }
        
        public WSDerechosAutorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSDerechosAutorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSDerechosAutorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSDerechosAutorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ConsultarFotoHabilitada(int id) {
            return base.Channel.ConsultarFotoHabilitada(id);
        }
        
        public System.Threading.Tasks.Task<bool> ConsultarFotoHabilitadaAsync(int id) {
            return base.Channel.ConsultarFotoHabilitadaAsync(id);
        }
    }
}
