//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebConsultarVentas.ServicioVentas {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Services/", ConfigurationName="ServicioVentas.ServicioConsultarVenta")]
    public interface ServicioConsultarVenta {
        
        // CODEGEN: El parámetro 'entity' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://Services/ServicioConsultarVenta/remove")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(find))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(edit))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(remove))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findAll))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(create))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(count))]
        void remove(WebConsultarVentas.ServicioVentas.remove1 request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://Services/ServicioConsultarVenta/remove")]
        System.Threading.Tasks.Task removeAsync(WebConsultarVentas.ServicioVentas.remove1 request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Services/ServicioConsultarVenta/countRequest", ReplyAction="http://Services/ServicioConsultarVenta/countResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(find))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(edit))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(remove))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findAll))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(create))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(count))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebConsultarVentas.ServicioVentas.countResponse1 count(WebConsultarVentas.ServicioVentas.countRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services/ServicioConsultarVenta/countRequest", ReplyAction="http://Services/ServicioConsultarVenta/countResponse")]
        System.Threading.Tasks.Task<WebConsultarVentas.ServicioVentas.countResponse1> countAsync(WebConsultarVentas.ServicioVentas.countRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Services/ServicioConsultarVenta/findRequest", ReplyAction="http://Services/ServicioConsultarVenta/findResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(find))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(edit))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(remove))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findAll))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(create))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(count))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebConsultarVentas.ServicioVentas.findResponse1 find(WebConsultarVentas.ServicioVentas.findRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services/ServicioConsultarVenta/findRequest", ReplyAction="http://Services/ServicioConsultarVenta/findResponse")]
        System.Threading.Tasks.Task<WebConsultarVentas.ServicioVentas.findResponse1> findAsync(WebConsultarVentas.ServicioVentas.findRequest request);
        
        // CODEGEN: El parámetro 'entity' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://Services/ServicioConsultarVenta/create")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(find))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(edit))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(remove))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findAll))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(create))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(count))]
        void create(WebConsultarVentas.ServicioVentas.create1 request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://Services/ServicioConsultarVenta/create")]
        System.Threading.Tasks.Task createAsync(WebConsultarVentas.ServicioVentas.create1 request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Services/ServicioConsultarVenta/findAllRequest", ReplyAction="http://Services/ServicioConsultarVenta/findAllResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(find))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(edit))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(remove))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findAll))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(create))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(count))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebConsultarVentas.ServicioVentas.findAllResponse findAll(WebConsultarVentas.ServicioVentas.findAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services/ServicioConsultarVenta/findAllRequest", ReplyAction="http://Services/ServicioConsultarVenta/findAllResponse")]
        System.Threading.Tasks.Task<WebConsultarVentas.ServicioVentas.findAllResponse> findAllAsync(WebConsultarVentas.ServicioVentas.findAllRequest request);
        
        // CODEGEN: El parámetro 'entity' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://Services/ServicioConsultarVenta/edit")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(find))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(edit))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(remove))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findAll))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(create))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(count))]
        void edit(WebConsultarVentas.ServicioVentas.edit1 request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://Services/ServicioConsultarVenta/edit")]
        System.Threading.Tasks.Task editAsync(WebConsultarVentas.ServicioVentas.edit1 request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Services/ServicioConsultarVenta/findRangeRequest", ReplyAction="http://Services/ServicioConsultarVenta/findRangeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(find))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(edit))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(remove))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findAll))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(create))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(count))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebConsultarVentas.ServicioVentas.findRangeResponse findRange(WebConsultarVentas.ServicioVentas.findRangeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services/ServicioConsultarVenta/findRangeRequest", ReplyAction="http://Services/ServicioConsultarVenta/findRangeResponse")]
        System.Threading.Tasks.Task<WebConsultarVentas.ServicioVentas.findRangeResponse> findRangeAsync(WebConsultarVentas.ServicioVentas.findRangeRequest request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Services/")]
    public partial class venta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fechaField;
        
        private long idfotoField;
        
        private long idventaField;
        
        private bool idventaFieldSpecified;
        
        private int valorField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long idfoto {
            get {
                return this.idfotoField;
            }
            set {
                this.idfotoField = value;
                this.RaisePropertyChanged("idfoto");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long idventa {
            get {
                return this.idventaField;
            }
            set {
                this.idventaField = value;
                this.RaisePropertyChanged("idventa");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idventaSpecified {
            get {
                return this.idventaFieldSpecified;
            }
            set {
                this.idventaFieldSpecified = value;
                this.RaisePropertyChanged("idventaSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
                this.RaisePropertyChanged("valor");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Services/")]
    public partial class findResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private venta returnField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public venta @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Services/")]
    public partial class find : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object idField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public object id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Services/")]
    public partial class edit : object, System.ComponentModel.INotifyPropertyChanged {
        
        private venta entityField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public venta entity {
            get {
                return this.entityField;
            }
            set {
                this.entityField = value;
                this.RaisePropertyChanged("entity");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Services/")]
    public partial class remove : object, System.ComponentModel.INotifyPropertyChanged {
        
        private venta entityField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public venta entity {
            get {
                return this.entityField;
            }
            set {
                this.entityField = value;
                this.RaisePropertyChanged("entity");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Services/")]
    public partial class fechaVenta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fechaConsultaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string fechaConsulta {
            get {
                return this.fechaConsultaField;
            }
            set {
                this.fechaConsultaField = value;
                this.RaisePropertyChanged("fechaConsulta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Services/")]
    public partial class findAll : object, System.ComponentModel.INotifyPropertyChanged {
        
        private fechaVenta arg0Field;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public fechaVenta arg0 {
            get {
                return this.arg0Field;
            }
            set {
                this.arg0Field = value;
                this.RaisePropertyChanged("arg0");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Services/")]
    public partial class create : object, System.ComponentModel.INotifyPropertyChanged {
        
        private venta entityField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public venta entity {
            get {
                return this.entityField;
            }
            set {
                this.entityField = value;
                this.RaisePropertyChanged("entity");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Services/")]
    public partial class countResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int returnField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Services/")]
    public partial class count : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="remove", WrapperNamespace="http://Services/", IsWrapped=true)]
    public partial class remove1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebConsultarVentas.ServicioVentas.venta entity;
        
        public remove1() {
        }
        
        public remove1(WebConsultarVentas.ServicioVentas.venta entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="count", WrapperNamespace="http://Services/", IsWrapped=true)]
    public partial class countRequest {
        
        public countRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="countResponse", WrapperNamespace="http://Services/", IsWrapped=true)]
    public partial class countResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public countResponse1() {
        }
        
        public countResponse1(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="find", WrapperNamespace="http://Services/", IsWrapped=true)]
    public partial class findRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object id;
        
        public findRequest() {
        }
        
        public findRequest(object id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findResponse", WrapperNamespace="http://Services/", IsWrapped=true)]
    public partial class findResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebConsultarVentas.ServicioVentas.venta @return;
        
        public findResponse1() {
        }
        
        public findResponse1(WebConsultarVentas.ServicioVentas.venta @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="create", WrapperNamespace="http://Services/", IsWrapped=true)]
    public partial class create1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebConsultarVentas.ServicioVentas.venta entity;
        
        public create1() {
        }
        
        public create1(WebConsultarVentas.ServicioVentas.venta entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAll", WrapperNamespace="http://Services/", IsWrapped=true)]
    public partial class findAllRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebConsultarVentas.ServicioVentas.fechaVenta arg0;
        
        public findAllRequest() {
        }
        
        public findAllRequest(WebConsultarVentas.ServicioVentas.fechaVenta arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAllResponse", WrapperNamespace="http://Services/", IsWrapped=true)]
    public partial class findAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebConsultarVentas.ServicioVentas.venta[] @return;
        
        public findAllResponse() {
        }
        
        public findAllResponse(WebConsultarVentas.ServicioVentas.venta[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="edit", WrapperNamespace="http://Services/", IsWrapped=true)]
    public partial class edit1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebConsultarVentas.ServicioVentas.venta entity;
        
        public edit1() {
        }
        
        public edit1(WebConsultarVentas.ServicioVentas.venta entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findRange", WrapperNamespace="http://Services/", IsWrapped=true)]
    public partial class findRangeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("range", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<int>[] range;
        
        public findRangeRequest() {
        }
        
        public findRangeRequest(System.Nullable<int>[] range) {
            this.range = range;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findRangeResponse", WrapperNamespace="http://Services/", IsWrapped=true)]
    public partial class findRangeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebConsultarVentas.ServicioVentas.venta[] @return;
        
        public findRangeResponse() {
        }
        
        public findRangeResponse(WebConsultarVentas.ServicioVentas.venta[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioConsultarVentaChannel : WebConsultarVentas.ServicioVentas.ServicioConsultarVenta, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioConsultarVentaClient : System.ServiceModel.ClientBase<WebConsultarVentas.ServicioVentas.ServicioConsultarVenta>, WebConsultarVentas.ServicioVentas.ServicioConsultarVenta {
        
        public ServicioConsultarVentaClient() {
        }
        
        public ServicioConsultarVentaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioConsultarVentaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioConsultarVentaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioConsultarVentaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void WebConsultarVentas.ServicioVentas.ServicioConsultarVenta.remove(WebConsultarVentas.ServicioVentas.remove1 request) {
            base.Channel.remove(request);
        }
        
        public void remove(WebConsultarVentas.ServicioVentas.venta entity) {
            WebConsultarVentas.ServicioVentas.remove1 inValue = new WebConsultarVentas.ServicioVentas.remove1();
            inValue.entity = entity;
            ((WebConsultarVentas.ServicioVentas.ServicioConsultarVenta)(this)).remove(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task WebConsultarVentas.ServicioVentas.ServicioConsultarVenta.removeAsync(WebConsultarVentas.ServicioVentas.remove1 request) {
            return base.Channel.removeAsync(request);
        }
        
        public System.Threading.Tasks.Task removeAsync(WebConsultarVentas.ServicioVentas.venta entity) {
            WebConsultarVentas.ServicioVentas.remove1 inValue = new WebConsultarVentas.ServicioVentas.remove1();
            inValue.entity = entity;
            return ((WebConsultarVentas.ServicioVentas.ServicioConsultarVenta)(this)).removeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebConsultarVentas.ServicioVentas.countResponse1 WebConsultarVentas.ServicioVentas.ServicioConsultarVenta.count(WebConsultarVentas.ServicioVentas.countRequest request) {
            return base.Channel.count(request);
        }
        
        public int count() {
            WebConsultarVentas.ServicioVentas.countRequest inValue = new WebConsultarVentas.ServicioVentas.countRequest();
            WebConsultarVentas.ServicioVentas.countResponse1 retVal = ((WebConsultarVentas.ServicioVentas.ServicioConsultarVenta)(this)).count(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebConsultarVentas.ServicioVentas.countResponse1> WebConsultarVentas.ServicioVentas.ServicioConsultarVenta.countAsync(WebConsultarVentas.ServicioVentas.countRequest request) {
            return base.Channel.countAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebConsultarVentas.ServicioVentas.countResponse1> countAsync() {
            WebConsultarVentas.ServicioVentas.countRequest inValue = new WebConsultarVentas.ServicioVentas.countRequest();
            return ((WebConsultarVentas.ServicioVentas.ServicioConsultarVenta)(this)).countAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebConsultarVentas.ServicioVentas.findResponse1 WebConsultarVentas.ServicioVentas.ServicioConsultarVenta.find(WebConsultarVentas.ServicioVentas.findRequest request) {
            return base.Channel.find(request);
        }
        
        public WebConsultarVentas.ServicioVentas.venta find(object id) {
            WebConsultarVentas.ServicioVentas.findRequest inValue = new WebConsultarVentas.ServicioVentas.findRequest();
            inValue.id = id;
            WebConsultarVentas.ServicioVentas.findResponse1 retVal = ((WebConsultarVentas.ServicioVentas.ServicioConsultarVenta)(this)).find(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebConsultarVentas.ServicioVentas.findResponse1> WebConsultarVentas.ServicioVentas.ServicioConsultarVenta.findAsync(WebConsultarVentas.ServicioVentas.findRequest request) {
            return base.Channel.findAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebConsultarVentas.ServicioVentas.findResponse1> findAsync(object id) {
            WebConsultarVentas.ServicioVentas.findRequest inValue = new WebConsultarVentas.ServicioVentas.findRequest();
            inValue.id = id;
            return ((WebConsultarVentas.ServicioVentas.ServicioConsultarVenta)(this)).findAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void WebConsultarVentas.ServicioVentas.ServicioConsultarVenta.create(WebConsultarVentas.ServicioVentas.create1 request) {
            base.Channel.create(request);
        }
        
        public void create(WebConsultarVentas.ServicioVentas.venta entity) {
            WebConsultarVentas.ServicioVentas.create1 inValue = new WebConsultarVentas.ServicioVentas.create1();
            inValue.entity = entity;
            ((WebConsultarVentas.ServicioVentas.ServicioConsultarVenta)(this)).create(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task WebConsultarVentas.ServicioVentas.ServicioConsultarVenta.createAsync(WebConsultarVentas.ServicioVentas.create1 request) {
            return base.Channel.createAsync(request);
        }
        
        public System.Threading.Tasks.Task createAsync(WebConsultarVentas.ServicioVentas.venta entity) {
            WebConsultarVentas.ServicioVentas.create1 inValue = new WebConsultarVentas.ServicioVentas.create1();
            inValue.entity = entity;
            return ((WebConsultarVentas.ServicioVentas.ServicioConsultarVenta)(this)).createAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebConsultarVentas.ServicioVentas.findAllResponse WebConsultarVentas.ServicioVentas.ServicioConsultarVenta.findAll(WebConsultarVentas.ServicioVentas.findAllRequest request) {
            return base.Channel.findAll(request);
        }
        
        public WebConsultarVentas.ServicioVentas.venta[] findAll(WebConsultarVentas.ServicioVentas.fechaVenta arg0) {
            WebConsultarVentas.ServicioVentas.findAllRequest inValue = new WebConsultarVentas.ServicioVentas.findAllRequest();
            inValue.arg0 = arg0;
            WebConsultarVentas.ServicioVentas.findAllResponse retVal = ((WebConsultarVentas.ServicioVentas.ServicioConsultarVenta)(this)).findAll(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebConsultarVentas.ServicioVentas.findAllResponse> WebConsultarVentas.ServicioVentas.ServicioConsultarVenta.findAllAsync(WebConsultarVentas.ServicioVentas.findAllRequest request) {
            return base.Channel.findAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebConsultarVentas.ServicioVentas.findAllResponse> findAllAsync(WebConsultarVentas.ServicioVentas.fechaVenta arg0) {
            WebConsultarVentas.ServicioVentas.findAllRequest inValue = new WebConsultarVentas.ServicioVentas.findAllRequest();
            inValue.arg0 = arg0;
            return ((WebConsultarVentas.ServicioVentas.ServicioConsultarVenta)(this)).findAllAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void WebConsultarVentas.ServicioVentas.ServicioConsultarVenta.edit(WebConsultarVentas.ServicioVentas.edit1 request) {
            base.Channel.edit(request);
        }
        
        public void edit(WebConsultarVentas.ServicioVentas.venta entity) {
            WebConsultarVentas.ServicioVentas.edit1 inValue = new WebConsultarVentas.ServicioVentas.edit1();
            inValue.entity = entity;
            ((WebConsultarVentas.ServicioVentas.ServicioConsultarVenta)(this)).edit(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task WebConsultarVentas.ServicioVentas.ServicioConsultarVenta.editAsync(WebConsultarVentas.ServicioVentas.edit1 request) {
            return base.Channel.editAsync(request);
        }
        
        public System.Threading.Tasks.Task editAsync(WebConsultarVentas.ServicioVentas.venta entity) {
            WebConsultarVentas.ServicioVentas.edit1 inValue = new WebConsultarVentas.ServicioVentas.edit1();
            inValue.entity = entity;
            return ((WebConsultarVentas.ServicioVentas.ServicioConsultarVenta)(this)).editAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebConsultarVentas.ServicioVentas.findRangeResponse WebConsultarVentas.ServicioVentas.ServicioConsultarVenta.findRange(WebConsultarVentas.ServicioVentas.findRangeRequest request) {
            return base.Channel.findRange(request);
        }
        
        public WebConsultarVentas.ServicioVentas.venta[] findRange(System.Nullable<int>[] range) {
            WebConsultarVentas.ServicioVentas.findRangeRequest inValue = new WebConsultarVentas.ServicioVentas.findRangeRequest();
            inValue.range = range;
            WebConsultarVentas.ServicioVentas.findRangeResponse retVal = ((WebConsultarVentas.ServicioVentas.ServicioConsultarVenta)(this)).findRange(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebConsultarVentas.ServicioVentas.findRangeResponse> WebConsultarVentas.ServicioVentas.ServicioConsultarVenta.findRangeAsync(WebConsultarVentas.ServicioVentas.findRangeRequest request) {
            return base.Channel.findRangeAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebConsultarVentas.ServicioVentas.findRangeResponse> findRangeAsync(System.Nullable<int>[] range) {
            WebConsultarVentas.ServicioVentas.findRangeRequest inValue = new WebConsultarVentas.ServicioVentas.findRangeRequest();
            inValue.range = range;
            return ((WebConsultarVentas.ServicioVentas.ServicioConsultarVenta)(this)).findRangeAsync(inValue);
        }
    }
}
